### ISSUE TITLE
configured inputs do not persist

### ISSUE THREAD

**Issue by MrMarvin** [Graylog2/graylog2-images#51] opened 2015-04-17 17:30 UTC
We were running a docker container using the suggested command line:
```
docker run -e GRAYLOG_PASSWORD=secret -p 5556:5555 -p 515:514 -p 9000:9000 -p 12202:12201 -v /graylog/data:/var/opt/graylog/data -v /graylog/logs:/var/log/graylog graylog2/allinone
```
and expected my changes to Graylog to be persistent from one `docker run` to another. However, Graylog settings like configured inputs are gone after running the container once more.

It appears to me that the inputs are stored in the MongoDB. Is this correct?
When doing a grep for the name of my configured input on the docker host: 
```
root@srv1-graylog1:# grep -nre "marfris" /graylog/data/
Binary file /graylog/data/mongodb/graylog.0 matches
```
Still, there is no input configured when running the container a second time.

Other data like collected logs are persistent though.

**Comment by couillardcharles** [comment] 2015-04-18 14:59
Hi, i've the same problem. Any solution to persist the inputs config?

**Comment by mariussturm** [comment] 2015-04-20 08:34
Yes the inputs are stored in MongoDB. The problem is that they are associated through the servers node-id with a defined server instance. So every time you start a complete new container based on an old database, you get a new server node-id and the old inputs don't belong  to this server instance anymore. The idea was to just stop and start containers. In this way the node-id should be the same.

**Comment by MrMarvin** [comment] 2015-04-20 09:09
Ah, I see now. 
So when using global inputs instead, they persist for every container instance I assume?!
Although it's kind of is obvious, I feel like this should be documented in the `docker/README.md`.

**Comment by mariussturm** [comment] 2015-04-20 09:12
Global means that a cluster of Graylog servers will all start the same input. But they are still bound to a node-id. Yep, will drop a line in the docs.

**Comment by mariussturm** [comment] 2015-04-21 10:15
Closing now because no real issue. Documentation is added.

**Comment by tzz** [comment] 2015-04-29 19:01
@mariussturm does specifying a container name with `--name mycontainer` set the node ID persistently?  Or is it tied to something else?

**Comment by mariussturm** [comment] 2015-04-30 08:43
do you mean `docker run --name ...`? That is not used inside of the container.

**Comment by tzz** [comment] 2015-04-30 12:02
I actually meant `docker run --hostname=myname`, sorry.  That sets the hostname as far as all the apps inside the container are concerned so maybe it can be used to persist the settings.

**Comment by mariussturm** [comment] 2015-04-30 12:28
I think the cleanest solution would be to introduce a new container option for it. So people could provide the node-id through another environment variable.

**Comment by tzz** [comment] 2015-04-30 15:53
Works for me :)  I just thought setting the hostname (which typically is a random string if you don't provide it explicitly) might be a nice way to provide the node ID.  It would be nice to use the same node ID for ES as well, actually, so you can identify it easily in the ES logs.

**Comment by mariussturm** [comment] 2015-05-03 13:50
Could you please pull the latest image and provide this parameter when starting the container: `-e GRAYLOG_NODE_ID=30833ff4-f14c-4641-8001-0866ac439552` (randomize the ID string!) This should now set the node ID to defined value. When the container is recreated on top of old data you can re-use the same ID. This should persist even inputs.

**Comment by sheavner** [comment] 2015-05-14 17:22
I grabbed the nodeid from the currenlty running node and passed that in after a container destroy and restart.    There is now a node running with that old id.

I can't verify that the inputs are working, because I've setup mine to be global (started on all nodes) so they always come back even without the persisted node id.

I have a different issue.  I have one custom user.  That user exists, but I can't login and get invalid credentials.   After each restart I have to go to System > Users  and update the password for this user.   And then things are fine.   The persistent GRAYLOG_NODE_ID didn't fix this.

**Comment by tzz** [comment] 2015-05-20 15:43
@sheavner how do you grab the node ID of a running node?  I didn't find that in the docs and it's not obvious from the Graylog UI.  Thanks!

The invalid user password is definitely inconvenient but not as bad as losing data. I hope it can be resolved.

**Comment by mariussturm** [comment] 2015-05-21 09:02
Ok, thanks for the feedback! I think we have to expose the `password_secret` as well. Will take a look soon.

**Comment by sheavner** [comment] 2015-05-22 07:09
@tzz  If there's only one node, it's obvious from the system messages on the System Overview page at  /system?page=0.    I think I found mine on /system/nodes which shows the short hash + nodename.  If you click on the node name, you can get the full nodeid from the url as you're viewing the node details.

**Comment by tzz** [comment] 2015-05-22 14:41
Thanks @mariussturm I found it now.  I knew the short version (which I saw elsewhere) was not enough but didn't notice the node detail page.  I'll wait for the password secret but otherwise this persistence is a great feature.

**Comment by mariussturm** [comment] 2015-05-26 13:27
Could you please pull the latest image and add this parameter to set the server password salt: `-e GRAYLOG_SERVER_SECRET=somerandomstring`
Next time you spin up the container with the same secret the user password should work.

**Comment by sheavner** [comment] 2015-05-26 20:17
@mariussturm My non-admin user password did persist across a test restart of the server after the pull.   Thanks for fixing this.

**Comment by mariussturm** [comment] 2015-05-27 08:59
Thanks for testing!

**Closed by mariussturm** 2015-05-27 08:59 UTC

**Comment by NahumLitvin** [comment] 2015-11-16 08:48
im trying to run the following docker config on windows7 machine.

[graylog_docker.txt](https://github.com/Graylog2/graylog2-images/files/35285/graylog_docker.txt)

but instead of presisting the data I get a "No Graylog servers available. Cannot log in." message....
