### ISSUE TITLE
AWS image gives 502 bad gateway out of the box

### ISSUE THREAD

**Issue by refreshingapathy** [Graylog2/graylog2-images#29] opened 2015-02-19 15:36 UTC
Out of the box, the AWS image for 1.0 gives a 502 error with nginx. 

Reproduce: 
1. Follow link for ami-f4f4a29c, deploy instance
2. Run sudo graylog-ctl reconfigure
3. Edit AWS security group to allow HTTP from my IP
4. Visit public IP, get 502 error.

 nginx error.log shows:
2015/02/19 15:25:19 [error] 2072#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: MYIP, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9000/", host: "MYPUBLICIPONAWS"

netstat shows that nothing is actually listening on port 9000.

Am I doing something wrong here? Thanks for any pointers.

**Comment by mariussturm** [comment] 2015-02-19 16:01
Thanks for the report! I can reproduce the issue, will take a look!

**Comment by mariussturm** [comment] 2015-02-19 18:42
Fixed in the latest AMIs, please give ami-ee194886 another try!

**Closed by mariussturm** 2015-02-19 18:42 UTC

**Comment by fzinken** [comment] 2015-02-24 14:09
Hi Marius,

I actually have the same issue on the ova appliance. After installation/setup it looks like most services are running but no server on port 9000 and therefore nginx throwing "bad gateway".

ubuntu@graylog:~$ netstat -a | grep LISTEN
tcp        0      0 localhost:afs3-callback *:*                     LISTEN     
tcp        0      0 *:35940                 *:*                     LISTEN     
tcp        0      0 *:3333                  *:*                     LISTEN     
tcp        0      0 *:27017                 *:*                     LISTEN     
tcp        0      0 localhost:2380          *:*                     LISTEN     
tcp        0      0 *:50766                 *:*                     LISTEN     
tcp        0      0 *:http                  *:*                     LISTEN     
tcp        0      0 graylog.my.hk:9200      *:*                     LISTEN     
tcp        0      0 graylog.my.hk:9300      *:*                     LISTEN     
tcp        0      0 *:ssh                   *:*                     LISTEN     
tcp6       0      0 [::]:4001               [::]:*                  LISTEN     
tcp6       0      0 [::]:12900              [::]:*                  LISTEN     
tcp6       0      0 [::]:9350               [::]:*                  LISTEN     
tcp6       0      0 [::]:2379               [::]:*                  LISTEN     
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN 

Cheers

Fred

**Comment by mariussturm** [comment] 2015-02-24 14:15
Could you please provide logs for elasticsearch and graylog-server? You can find them under `/var/log/graylog/elasticsearch/current` and `/var/log/graylog/server/current`

**Comment by fzinken** [comment] 2015-02-24 14:34
Hi Marius,

seems I can not attach them so here they come:

1. server.current
2015-02-24_14:22:35.87486 It looks like you are trying to access MongoDB over HTTP on the native driver port.
2015-02-24_14:22:43.66243 2015-02-24 22:22:43,656 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugins: []
2015-02-24_14:22:44.34195 2015-02-24 22:22:44,341 INFO : org.graylog2.bootstrap.CmdLineTool - Running with JVM arguments: -Xms1g -Xmx1g -XX:NewRatio=1 -XX:PermSize=128m -XX:MaxPermSize=256m -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow
2015-02-24_14:22:51.80420 2015-02-24 22:22:51,803 INFO : org.graylog2.shared.system.stats.SigarService - Failed to load SIGAR. Falling back to JMX implementations.
2015-02-24_14:23:08.61748 2015-02-24 22:23:08,616 INFO : org.graylog2.shared.buffers.InputBufferImpl - Message journal is enabled.
2015-02-24_14:23:10.69121 2015-02-24 22:23:10,690 INFO : kafka.log.LogManager - Found clean shutdown file. Skipping recovery for all logs in data directory '/var/opt/graylog/data/journal'
2015-02-24_14:23:10.69907 2015-02-24 22:23:10,698 INFO : kafka.log.LogManager - Loading log 'messagejournal-0'
2015-02-24_14:23:10.96003 2015-02-24 22:23:10,959 INFO : kafka.log.Log - Completed load of log messagejournal-0 with log end offset 0
2015-02-24_14:23:11.07648 2015-02-24 22:23:11,076 INFO : org.graylog2.shared.journal.KafkaJournal - Initialized Kafka based journal at /var/opt/graylog/data/journal
2015-02-24_14:23:11.14895 2015-02-24 22:23:11,148 INFO : org.graylog2.shared.buffers.InputBufferImpl - Initialized InputBufferImpl with ring size <65536> and wait strategy <BlockingWaitStrategy>, running 2 parallel message handlers.
2015-02-24_14:23:12.79726 2015-02-24 22:23:12,796 INFO : org.graylog2.plugin.system.NodeId - Node ID: 7bf0d3d9-abce-48e6-becf-8a0c1305ed34
2015-02-24_14:23:14.44770 2015-02-24 22:23:14,446 INFO : org.elasticsearch.node - [graylog2-server] version[1.3.7], pid[822], build[3042293/2014-12-16T13:59:32Z]
2015-02-24_14:23:14.46696 2015-02-24 22:23:14,466 INFO : org.elasticsearch.node - [graylog2-server] initializing ...
2015-02-24_14:23:14.58807 2015-02-24 22:23:14,587 INFO : org.elasticsearch.plugins - [graylog2-server] loaded [graylog2-monitor], sites []
2015-02-24_14:23:38.76127 2015-02-24 22:23:38,760 INFO : org.elasticsearch.node - [graylog2-server] initialized
2015-02-24_14:23:38.81697 2015-02-24 22:23:38,816 INFO : org.graylog2.shared.buffers.ProcessBuffer - Initialized ProcessBuffer with ring size <1024> and wait strategy <BlockingWaitStrategy>.
2015-02-24_14:23:47.78924 2015-02-24 22:23:47,788 INFO : org.drools.compiler.kie.builder.impl.KieRepositoryImpl - KieModule was added:MemoryKieModule[ ReleaseId=org.graylog2:dynamic-rules:0]
2015-02-24_14:23:48.13503 2015-02-24 22:23:48,134 INFO : org.drools.compiler.kie.builder.impl.KieRepositoryImpl - Adding KieModule from resource :[ByteArrayResource resource=[B@27d115f8]
2015-02-24_14:23:48.85457 2015-02-24 22:23:48,854 INFO : org.drools.compiler.kie.builder.impl.KieRepositoryImpl - KieModule was added:MemoryKieModule[ ReleaseId=org.graylog2:dynamic-rules:0]
2015-02-24_14:23:52.18310 2015-02-24 22:23:52,181 INFO : org.graylog2.bindings.providers.RulesEngineProvider - No static rules file loaded.
2015-02-24_14:23:52.53091 2015-02-24 22:23:52,530 INFO : org.graylog2.buffers.OutputBuffer - Initialized OutputBuffer with ring size <1024> and wait strategy <BlockingWaitStrategy>.
2015-02-24_14:23:56.28257 2015-02-24 22:23:56,281 INFO : org.graylog2.bootstrap.ServerBootstrap - Graylog server 1.0.0 (b8f7d53) starting up. (JRE: Oracle Corporation 1.7.0_71 on Linux 3.13.0-32-generic)
2015-02-24_14:23:56.76519 2015-02-24 22:23:56,498 INFO : org.graylog2.shared.initializers.PeriodicalsService - Starting 14 periodicals ...
2015-02-24_14:23:56.77455 2015-02-24 22:23:56,773 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.ThroughputCounterManagerThread] periodical in [0s], polling every [1s].
2015-02-24_14:23:56.77692 2015-02-24 22:23:56,572 INFO : org.elasticsearch.node - [graylog2-server] starting ...
2015-02-24_14:23:56.78037 2015-02-24 22:23:56,780 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.AlertScannerThread] periodical in [10s], polling every [60s].
2015-02-24_14:23:56.78132 2015-02-24 22:23:56,781 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.BatchedElasticSearchOutputFlushThread] periodical in [0s], polling every [1s].
2015-02-24_14:23:56.81614 2015-02-24 22:23:56,815 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.ClusterHealthCheckThread] periodical in [0s], polling every [20s].
2015-02-24_14:23:56.82429 2015-02-24 22:23:56,824 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.ContentPackLoaderPeriodical] periodical, running forever.
2015-02-24_14:23:56.83914 2015-02-24 22:23:56,838 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.DeadLetterThread] periodical, running forever.
2015-02-24_14:23:56.85669 2015-02-24 22:23:56,856 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.GarbageCollectionWarningThread] periodical, running forever.
2015-02-24_14:23:56.86575 2015-02-24 22:23:56,865 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.IndexerClusterCheckerThread] periodical in [0s], polling every [30s].
2015-02-24_14:23:56.86702 2015-02-24 22:23:56,866 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.IndexRetentionThread] periodical in [0s], polling every [300s].
2015-02-24_14:23:56.92165 2015-02-24 22:23:56,921 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.IndexRotationThread] periodical in [0s], polling every [10s].
2015-02-24_14:23:56.92710 2015-02-24 22:23:56,924 INFO : org.graylog2.periodical.IndexRetentionThread - Elasticsearch cluster not available, skipping index retention checks.
2015-02-24_14:23:57.00425 2015-02-24 22:23:57,003 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.NodePingThread] periodical in [0s], polling every [1s].
2015-02-24_14:23:57.00580 2015-02-24 22:23:57,005 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.StreamThroughputCounterManagerThread] periodical in [0s], polling every [1s].
2015-02-24_14:23:57.02899 2015-02-24 22:23:57,028 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.VersionCheckThread] periodical in [0s], polling every [1800s].
2015-02-24_14:23:57.03021 2015-02-24 22:23:57,029 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.ThrottleStateUpdaterThread] periodical in [1s], polling every [1s].
2015-02-24_14:23:59.71502 2015-02-24 22:23:59,714 INFO : org.elasticsearch.transport - [graylog2-server] bound_address {inet[/0:0:0:0:0:0:0:0:9350]}, publish_address {inet[/192.168.147.151:9350]}
2015-02-24_14:24:00.22107 2015-02-24 22:24:00,220 INFO : org.elasticsearch.discovery - [graylog2-server] graylog2/X6TX32ddRu2zu6ePRtYthw
2015-02-24_14:24:00.35890 2015-02-24 22:24:00,358 WARN : org.graylog2.indexer.esplugin.ClusterStateMonitor - No Elasticsearch data nodes in cluster, cluster is completely offline.
2015-02-24_14:24:02.26255 2015-02-24 22:24:02,262 INFO : org.reflections.Reflections - Reflections took 4785 ms to scan 1 urls, producing 2 keys and 2 values 
2015-02-24_14:24:03.34631 2015-02-24 22:24:03,345 WARN : org.elasticsearch.discovery - [graylog2-server] waited for 3s and no initial state was set by the discovery
2015-02-24_14:24:03.35801 2015-02-24 22:24:03,357 INFO : org.elasticsearch.node - [graylog2-server] started
2015-02-24_14:24:05.61705 2015-02-24 22:24:05,615 INFO : org.elasticsearch.cluster.service - [graylog2-server] detected_master [Phantom Blonde][CjN0wkg-Qs-pe2wJY6ts9w][graylog][inet[/192.168.147.151:9300]], added {[Phantom Blonde][CjN0wkg-Qs-pe2wJY6ts9w][graylog][inet[/192.168.147.151:9300]],}, reason: zen-disco-receive(from master [[Phantom Blonde][CjN0wkg-Qs-pe2wJY6ts9w][graylog][inet[/192.168.147.151:9300]]])
2015-02-24_14:24:48.93051 2015-02-24 22:24:48,929 WARN : org.elasticsearch.monitor.jvm - [graylog2-server] [gc][young][51][2] duration [1.5s], collections [1]/[1.6s], total [1.5s]/[2.6s], memory [475.6mb]->[79.9mb]/[972.8mb], all_pools {[young] [409.6mb]->[4.1mb]/[409.6mb]}{[survivor] [51.1mb]->[32.6mb]/[51.1mb]}{[old] [14.8mb]->[43.1mb]/[512mb]}
2015-02-24_14:24:49.71436 2015-02-24 22:24:49,713 INFO : org.graylog2.shared.initializers.RestApiService - Adding security context factory: <org.graylog2.security.ShiroSecurityContextFactory@e3f7131>
2015-02-24_14:24:49.90728 2015-02-24 22:24:49,906 INFO : org.graylog2.shared.initializers.RestApiService - Started REST API at <http://0.0.0.0:12900/>
2015-02-24_14:24:49.91861 2015-02-24 22:24:49,918 INFO : org.graylog2.shared.initializers.ServiceManagerListener - Services are healthy
2015-02-24_14:24:49.93503 2015-02-24 22:24:49,934 INFO : org.graylog2.shared.initializers.InputSetupService - Triggering launching persisted inputs, node transitioned from Uninitialized?[LB:DEAD] to Running?[LB:ALIVE]
2015-02-24_14:24:49.96363 2015-02-24 22:24:49,963 INFO : org.graylog2.bootstrap.ServerBootstrap - Services started, startup times in ms: {DashboardRegistryService [RUNNING]=124, OutputSetupService [RUNNING]=134, BufferSynchronizerService [RUNNING]=166, MetricsReporterService [RUNNING]=169, JournalReader [RUNNING]=184, InputSetupService [RUNNING]=185, GroovyShellSetupService [RUNNING]=190, KafkaJournal [RUNNING]=195, PeriodicalsService [RUNNING]=558, IndexerSetupService [RUNNING]=9561, RestApiService [RUNNING]=53413}
2015-02-24_14:24:50.12854 2015-02-24 22:24:50,128 INFO : org.graylog2.bootstrap.ServerBootstrap - Graylog server up and running.


2. elasticsearch.current
2015-02-24_14:22:12.12962 getopt: invalid option -- 'f'
2015-02-24_14:22:26.98717 log4j:ERROR setFile(null,true) call failed.
2015-02-24_14:22:26.99399 java.io.FileNotFoundException: /opt/graylog/elasticsearch/logs/graylog2.log (No such file or directory)
2015-02-24_14:22:26.99541 	at java.io.FileOutputStream.open(Native Method)
2015-02-24_14:22:26.99629 	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
2015-02-24_14:22:26.99714 	at java.io.FileOutputStream.<init>(FileOutputStream.java:142)
2015-02-24_14:22:27.00126 	at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
2015-02-24_14:22:27.00216 	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
2015-02-24_14:22:27.00288 	at org.apache.log4j.DailyRollingFileAppender.activateOptions(DailyRollingFileAppender.java:223)
2015-02-24_14:22:27.00357 	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
2015-02-24_14:22:27.00605 	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:172)
2015-02-24_14:22:27.00681 	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:104)
2015-02-24_14:22:27.00805 	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:842)
2015-02-24_14:22:27.00881 	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
2015-02-24_14:22:27.00947 	at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:648)
2015-02-24_14:22:27.01028 	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:514)
2015-02-24_14:22:27.01126 	at org.apache.log4j.PropertyConfigurator.configure(PropertyConfigurator.java:440)
2015-02-24_14:22:27.01197 	at org.elasticsearch.common.logging.log4j.LogConfigurator.configure(LogConfigurator.java:105)
2015-02-24_14:22:27.01268 	at org.elasticsearch.bootstrap.Bootstrap.setupLogging(Bootstrap.java:94)
2015-02-24_14:22:27.01800 	at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:178)
2015-02-24_14:22:27.01806 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)
2015-02-24_14:22:27.01810 log4j:ERROR Either File or DatePattern options are not set for appender [file].
2015-02-24_14:22:27.02295 log4j:ERROR setFile(null,true) call failed.
2015-02-24_14:22:27.02375 java.io.FileNotFoundException: /opt/graylog/elasticsearch/logs/graylog2_index_indexing_slowlog.log (No such file or directory)
2015-02-24_14:22:27.02450 	at java.io.FileOutputStream.open(Native Method)
2015-02-24_14:22:27.02516 	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
2015-02-24_14:22:27.02608 	at java.io.FileOutputStream.<init>(FileOutputStream.java:142)
2015-02-24_14:22:27.02671 	at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
2015-02-24_14:22:27.02747 	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
2015-02-24_14:22:27.02819 	at org.apache.log4j.DailyRollingFileAppender.activateOptions(DailyRollingFileAppender.java:223)
2015-02-24_14:22:27.02888 	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
2015-02-24_14:22:27.02961 	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:172)
2015-02-24_14:22:27.03069 	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:104)
2015-02-24_14:22:27.03146 	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:842)
2015-02-24_14:22:27.03213 	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
2015-02-24_14:22:27.03286 	at org.apache.log4j.PropertyConfigurator.parseCatsAndRenderers(PropertyConfigurator.java:672)
2015-02-24_14:22:27.03353 	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:516)
2015-02-24_14:22:27.03464 	at org.apache.log4j.PropertyConfigurator.configure(PropertyConfigurator.java:440)
2015-02-24_14:22:27.03530 	at org.elasticsearch.common.logging.log4j.LogConfigurator.configure(LogConfigurator.java:105)
2015-02-24_14:22:27.03597 	at org.elasticsearch.bootstrap.Bootstrap.setupLogging(Bootstrap.java:94)
2015-02-24_14:22:27.03678 	at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:178)
2015-02-24_14:22:27.03760 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)
2015-02-24_14:22:27.03857 log4j:ERROR Either File or DatePattern options are not set for appender [index_indexing_slow_log_file].
2015-02-24_14:22:27.04277 log4j:ERROR setFile(null,true) call failed.
2015-02-24_14:22:27.04357 java.io.FileNotFoundException: /opt/graylog/elasticsearch/logs/graylog2_index_search_slowlog.log (No such file or directory)
2015-02-24_14:22:27.04445 	at java.io.FileOutputStream.open(Native Method)
2015-02-24_14:22:27.04518 	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
2015-02-24_14:22:27.04617 	at java.io.FileOutputStream.<init>(FileOutputStream.java:142)
2015-02-24_14:22:27.04680 	at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
2015-02-24_14:22:27.04747 	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
2015-02-24_14:22:27.04862 	at org.apache.log4j.DailyRollingFileAppender.activateOptions(DailyRollingFileAppender.java:223)
2015-02-24_14:22:27.04933 	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
2015-02-24_14:22:27.05027 	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:172)
2015-02-24_14:22:27.05101 	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:104)
2015-02-24_14:22:27.05172 	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:842)
2015-02-24_14:22:27.05244 	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
2015-02-24_14:22:27.05318 	at org.apache.log4j.PropertyConfigurator.parseCatsAndRenderers(PropertyConfigurator.java:672)
2015-02-24_14:22:27.05404 	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:516)
2015-02-24_14:22:27.05473 	at org.apache.log4j.PropertyConfigurator.configure(PropertyConfigurator.java:440)
2015-02-24_14:22:27.05552 	at org.elasticsearch.common.logging.log4j.LogConfigurator.configure(LogConfigurator.java:105)
2015-02-24_14:22:27.05622 	at org.elasticsearch.bootstrap.Bootstrap.setupLogging(Bootstrap.java:94)
2015-02-24_14:22:27.05700 	at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:178)
2015-02-24_14:22:27.05764 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)
2015-02-24_14:22:27.05851 log4j:ERROR Either File or DatePattern options are not set for appender [index_search_slow_log_file].
2015-02-24_14:22:30.63365 [2015-02-24 22:22:30,626][INFO ][node                     ] [Phantom Blonde] version[1.4.1], pid[823], build[89d3241/2014-11-26T15:49:29Z]
2015-02-24_14:22:30.63476 [2015-02-24 22:22:30,634][INFO ][node                     ] [Phantom Blonde] initializing ...
2015-02-24_14:22:30.68280 [2015-02-24 22:22:30,682][INFO ][plugins                  ] [Phantom Blonde] loaded [], sites []
2015-02-24_14:23:01.03378 [2015-02-24 22:23:01,032][INFO ][node                     ] [Phantom Blonde] initialized
2015-02-24_14:23:01.03465 [2015-02-24 22:23:01,034][INFO ][node                     ] [Phantom Blonde] starting ...
2015-02-24_14:23:01.93349 [2015-02-24 22:23:01,933][INFO ][transport                ] [Phantom Blonde] bound_address {inet[/192.168.147.151:9300]}, publish_address {inet[/192.168.147.151:9300]}
2015-02-24_14:23:02.01787 [2015-02-24 22:23:02,017][INFO ][discovery                ] [Phantom Blonde] graylog2/CjN0wkg-Qs-pe2wJY6ts9w
2015-02-24_14:23:12.40840 [2015-02-24 22:23:12,393][INFO ][cluster.service          ] [Phantom Blonde] new_master [Phantom Blonde][CjN0wkg-Qs-pe2wJY6ts9w][graylog][inet[/192.168.147.151:9300]], reason: zen-disco-join (elected_as_master)
2015-02-24_14:23:12.87276 [2015-02-24 22:23:12,872][INFO ][http                     ] [Phantom Blonde] bound_address {inet[/192.168.147.151:9200]}, publish_address {inet[/192.168.147.151:9200]}
2015-02-24_14:23:12.87424 [2015-02-24 22:23:12,873][INFO ][node                     ] [Phantom Blonde] started
2015-02-24_14:23:22.53179 [2015-02-24 22:23:22,530][INFO ][gateway                  ] [Phantom Blonde] recovered [1] indices into cluster_state
2015-02-24_14:24:05.38014 [2015-02-24 22:24:05,379][INFO ][cluster.service          ] [Phantom Blonde] added {[graylog2-server][X6TX32ddRu2zu6ePRtYthw][graylog][inet[/192.168.147.151:9350]]{client=true, data=false, master=false},}, reason: zen-disco-receive(join from node[[graylog2-server][X6TX32ddRu2zu6ePRtYthw][graylog][inet[/192.168.147.151:9350]]{client=true, data=false, master=false}])



Cheers

Fred

**Comment by mariussturm** [comment] 2015-02-24 14:56
Mh, hard to say from here. There are no obvious errors in the logs so the server should be up and running. Did you make sure that the appliance got at least 4GB Ram and some decent CPU resources? Maybe you run in some timeout because of limited resources?

**Comment by fzinken** [comment] 2015-02-24 15:05
Hi Marius,

yes I gave the VM 4 GB RAM and 2 CPUs so it should be fine. But let me just try again to import the ova and start from scratch.

Cheers

Fred

**Comment by fzinken** [comment] 2015-02-24 16:12
Hi Marius,

FYI, after a fresh import of the appliance and the first boot the server works fine as expected. But after setting admin password/mail-server/timezone and calling reconfigure/restart the server on port 9000 is not starting up. I will try to investigate a bit more when I have time.

Cheers

Fred

**Comment by mariussturm** [comment] 2015-02-24 16:16
Ok, great!
Would be interesting to see which input is breaking the configuration to build-in some kind of validation!

**Comment by fzinken** [comment] 2015-02-25 05:41
Hi Marius,

the change of admin password and a restart works fine.
But
sudo graylog-ctl set-timezone HK
sudo graylog-ctl reconfigure
sudo graylog-ctl restart
seems to break it.

When I have time will do a few other test to dig in.

Cheers
Fred

**Comment by mariussturm** [comment] 2015-02-25 12:04
Thanks for the feedback!
You should see something like this in your web interface logs `sudo graylog-ctl tail web`:
`Caused by: java.lang.IllegalArgumentException: The datetime zone id 'HK' is not recognised`

You have to use the full name of the timezone in this case: `Asia/Hong_Kong`

For the next version of the appliance there will be a validation for unrecognised timezones.

**Comment by fzinken** [comment] 2015-02-25 12:17
Hi Marius,

yes I had that error in the logs and yes setting timezone to Asia/Hong_Kong fixed it.
Many thanks now I can continue my journey to understand graylog.

Cheers

Fred
