### ISSUE TITLE
I use official docker-compose.yml file and I've « Elasticsearch cluster unavailable » error message

### ISSUE THREAD

**Issue by harobed** [Graylog2/graylog2-images#161] opened 2016-08-20 09:40 UTC
Hi,

I use `docker-compose.yml` documented here: http://docs.graylog.org/en/latest/pages/installation/docker.html#settings

```
some-mongo:
  image: "mongo:3"
some-elasticsearch:
  image: "elasticsearch:2"
  command: "elasticsearch -Des.cluster.name='graylog'"
graylog:
  image: graylog2/server:2.0.0-1
  environment:
    GRAYLOG_PASSWORD_SECRET: somepasswordpepper
    GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
    GRAYLOG_REST_TRANSPORT_URI: http://127.0.0.1:12900
  links:
    - some-mongo:mongo
    - some-elasticsearch:elasticsearch
  ports:
    - "9000:9000"
    - "12900:12900"
```

and I've this error:

>  Elasticsearch cluster unavailable (triggered 2 hours ago)
> Graylog could not successfully connect to the Elasticsearch cluster. If you're using multicast, check that it is working in your network and that Elasticsearch is accessible. Also check that the cluster name setting is correct. Read how to fix this in the Elasticsearch setup documentation.

<img width="1639" alt="capture d ecran 2016-08-20 a 11 37 24" src="https://cloud.githubusercontent.com/assets/230143/17830416/d0d595d2-66ca-11e6-8a82-4295d48c40ca.png">

Is it a bug in Official Graylog Docker Image ?

**Comment by mariussturm** [comment] 2016-08-22 08:22
Tested this today and it worked fine for me. I am pretty sure this is related to your other issue #160 please check the logs of Elasticsearch why it isn't starting.

**Comment by mariussturm** [comment] 2016-08-23 09:07
Closing this for now, cant reproduce. Feel free to add more comments if you think this is still an error.

**Closed as completed by mariussturm** 2016-08-23 09:07 UTC
