### ISSUE TITLE
Problems importing the OVA file into vCenter 6.5

### ISSUE THREAD

**Issue by cormite** [Graylog2/graylog2-images#211] opened 2018-03-06 08:15 UTC
When importing the provided OVA file (version 2.4.3-1) into vCenter (or ESXi straight) I came across the following error:

`"The provided manifest file is invalid: Invalid OVF manifest entry: ."`

After a couple of investigations I realized that the problem came from the ResourceSubType PIIX4:
```
- 48:10:VALUE_ILLEGAL: Value ‘‘PIIX4’’ of ResourceSubType element not found in [].
- 57:10:VALUE_ILLEGAL: Value ‘‘PIIX4’’ of ResourceSubType element not found in [].
- 66:10:VALUE_ILLEGAL: Value ‘‘3’’ of Parent element does not refer to a ref of type DiskControllerReference.
```

Finally I was able to resolve the issue by modifying lines in the OVF file from lines 48 to lines 65 as follows:

Original block:
```
<Item>
    <rasd:Address>0</rasd:Address>
    <rasd:Caption>ideController0</rasd:Caption>
    <rasd:Description>IDE Controller</rasd:Description>
    <rasd:ElementName>ideController0</rasd:ElementName>
    <rasd:InstanceID>3</rasd:InstanceID>
    <rasd:ResourceSubType>PIIX4</rasd:ResourceSubType>
    <rasd:ResourceType>5</rasd:ResourceType>
 </Item>
 <Item>
    <rasd:Address>1</rasd:Address>
    <rasd:Caption>ideController1</rasd:Caption>
    <rasd:Description>IDE Controller</rasd:Description>
    <rasd:ElementName>ideController1</rasd:ElementName>
    <rasd:InstanceID>4</rasd:InstanceID>
    <rasd:ResourceSubType>PIIX4</rasd:ResourceSubType>
    <rasd:ResourceType>5</rasd:ResourceType>
 </Item>
```

Modified block:
```
<Item>
    <rasd:Address>0</rasd:Address>
    <rasd:Caption>SCSIController</rasd:Caption>
    <rasd:Description>SCSI Controller</rasd:Description>
    <rasd:ElementName>SCSIController</rasd:ElementName>
    <rasd:InstanceID>3</rasd:InstanceID>
    <rasd:ResourceSubType>lsilogic</rasd:ResourceSubType>
    <rasd:ResourceType>6</rasd:ResourceType>
</Item>
<Item>
    <rasd:Address>1</rasd:Address>
    <rasd:Caption>SCSIController</rasd:Caption>
    <rasd:Description>SCSI Controller</rasd:Description>
    <rasd:ElementName>SCSIController</rasd:ElementName>
    <rasd:InstanceID>4</rasd:InstanceID>
    <rasd:ResourceSubType>lsilogic</rasd:ResourceSubType>
    <rasd:ResourceType>6</rasd:ResourceType>
</Item>
```

I hope this helps others solve the importing of the virtual appliance into VMware environments.

Best regards,
Carlos.

**Comment by joschi** [comment] 2018-03-06 08:40
@cormite Which version of ESXi  and vCenter are you using exactly?

**Comment by cormite** [comment] 2018-03-06 09:08
@joschi 
I run: VMware vCenter Server Appliance 6.5.0.14100 Build Number 7801515
And for ESXi two versions:
- VMware ESXi, 6.5.0, 7526125
- VMware ESXi, 6.5.0, 5969303

Best regards,
Carlos.

**Comment by jalogisch** [comment] 2018-03-06 10:06
ref: https://community.graylog.org/t/graylog-ova-import-problems/4422/12

**Comment by casellia** [comment] 2018-05-17 12:46
Have you tried to directly access the ESX host and deploy the OVA file?

**Comment by cormite** [comment] 2018-05-17 14:11
Dear @casellia,

Please follow the ref. specified by @jalogisch (https://community.graylog.org/t/graylog-ova-import-problems/4422/12). This case was fixed and closed.

Thanks,
Carlos.

**Comment by jusromaine** [comment] 2019-01-27 02:09
Im getting this even with your fix Issues detected with selected template. Details: - 74:7:VALUE_ILLEGAL: Value ''6'' of Parent element does not refer to a ref of type DiskControllerReference.

**Comment by mariussturm** [comment] 2019-01-29 16:03
Hi,
could you please retry with the latest 3.0 beta image? In 3.0.0-beta-4 we removed the problematic sound card and switched from an IDE disk controller to a SATA one.

 https://packages.graylog2.org/releases/graylog-omnibus/ova/graylog-pre-3.0.0-9.beta.4.ova

**Comment by jusromaine** [comment] 2019-01-29 16:54
Was there anything I was supposed to do with it first because I got this with it as is.



Thanks

**Comment by nathjnair** [comment] 2019-01-30 08:12
> Hi,
> could you please retry with the latest 3.0 beta image? In 3.0.0-beta-4 we removed the problematic sound card and switched from an IDE disk controller to a SATA one.
> 
> https://packages.graylog2.org/releases/graylog-omnibus/ova/graylog-pre-3.0.0-9.beta.4.ova

Thank you for the help, tried the new beta OVA but encountered the following errors.
Line 57: No space left for device '7' on parent controller '5'.
Line 48: Unsupported virtual hardware device 'AHCI'.

**Comment by mariussturm** [comment] 2019-01-30 09:35
@nathjnair looks like the VirtualBox SATA controller is not supported by VmWare, so last option would be to be to use a SCSI controller instead. Will try this today.

**Comment by mariussturm** [comment] 2019-01-30 12:15
@nathjnair could you give rc.1 a try? It's using the scsi controller now and was tested successfully with Virtaulbox 5.2 and VMware Fusion 11  https://packages.graylog2.org/releases/graylog-omnibus/ova/graylog-pre-3.0.0-10.rc.1.ova

Unfortunately we dont have a vCenter installation available to fully reproduce your issues.

**Comment by nathjnair** [comment] 2019-01-31 11:09
> @nathjnair could you give rc.1 a try? It's using the scsi controller now and was tested successfully with Virtaulbox 5.2 and VMware Fusion 11 https://packages.graylog2.org/releases/graylog-omnibus/ova/graylog-pre-3.0.0-10.rc.1.ova
> 
> Unfortunately we dont have a vCenter installation available to fully reproduce your issues.

Hi mariussturn, Thank you for your help, the ova you mentioned is working.

By the way, I am not using vcenter setup, I am using the free version of ESXi 6.5

I have successfully able to bring up web gui, but the default username and password (admin/admin) is not working, tried to reset the password using graylog-ctl , but the command is not recognised by the system.

**Comment by mariussturm** [comment] 2019-01-31 12:31
@nathjnair ok cool, thanks for the feedback. Closing the issue for now.

**Closed as completed by mariussturm** 2019-01-31 12:31 UTC

**Comment by PukinDogs** [comment] 2020-03-05 17:02
Just tried to import the OVA for Graylog-3.2.2-1   using Vcenter 6.7.0 Build 10244857

I received the same manifest error 
`"The provided manifest file is invalid: Invalid OVF manifest entry: ."`

Unfortunately Editing OVF file from lines 48 to lines 65 with the above change did not fix the issue.
